esphome:
  name: esp32-2

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e080c8e88e98665eec680229a9c41016"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-2 Fallback Hotspot"
    password: "Z5p6wqWxnMsK"

captive_portal:



   
# Manuell ip. Får det INTE att fungera så ändra inte detta om du inte vet hur man gör.    
  #manual_ip:
    # Set this to the IP of the ESP
    #static_ip: 192.168.0.26
    # Set this to the IP address of the router. Often ends with .1
    #gateway: 192.168.0.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    #subnet: 255.255.255.0
    
    
# XXXXXXXXXXXXXX  SETUP  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# ESP32 for Touch
esp32_touch:

# i2C for BME280
i2c:
  sda: 21
  scl: 22
  
# SPI for HotTemp
spi:
  miso_pin: 19
  clk_pin: 5
# XXXXXXXXXXXXX END SETUP  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


# BINARY SENSORS INPUT -------------------------------------------------------------------
# Switch1
binary_sensor:
  - platform: gpio
    pin:
      number: 14                    # Momentanswitch
      mode:
       input: true
       pullup: true
    name: "Switch_1"
    on_press:
      then:
        - switch.toggle: relay_1_ID


  - platform: gpio
    pin: 
     number: 17                     # PIR motion sensor
    device_class: motion    
    name: "motion1"
    
  - platform: esp32_touch
    name: "Waterleak"
    pin: 27
    threshold: 1000
    
    
# SWITCHES OUTPUT -------------------------------------------------------------------
    
                                    # Relay_1
switch:
  - platform: gpio
    pin: 13   # OUTput LED
    name: "relay_1"
    id: relay_1_ID

 
#SENSOR---------------------------------------    
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76 #0x77
    update_interval: 5s

# LIGHT RESISTOR LDR-------------------------
# Rfixed = sqrt( Rdark x Rlight 1,4k)------------
  - platform: resistance
    sensor: source_sensor
    configuration: UPSTREAM
    resistor: 470Ohm
    name: Light
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
    - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
        - 1005.0 -> 100
        - 20200 -> 0.1


  - platform: adc
    id: source_sensor
    update_interval: 1s
    pin: 39

    
    
    
# LEDC----------------------------------------------
output:
  - platform: ledc
    pin: GPIO13
    frequency: 40000Hz
    id: LED_gpio_13

    
light:
  - platform: monochromatic
    name: "LEDpwm"
    default_transition_length: 3s
    output: LED_gpio_13